---
# This file defines the basic host groups.
# If you are planning host groups this may be day 1 configuration
# adding hosts to host groups is a deployment or registration time function

idm_host_groups:
  - name: "hg-production"
    description: "Production Servers"
  - name: "hg-qualification"
    description: "Quality assurance and testing servers"
  - name: "hg-development"
    description: "Development and research servers"
  - name: "hg-pipeline"
    description: "Pipeline and build servers"
  - name: "hg-satellite-primary-servers"
    description: "Satellite Servers"
  - name: "hg-satellite-capsule-servers"
    description: "Satellite Capsule servers"
  - name: "hg-aap-servers"
    description: "Ansible Automation Platform Servers"
  - name: "hg-container-hosts"
    description: "Container Hosts for running standalone containers e.g. tang, discovery, etc.."
