---

# Create DNS Records for non-idm registered hosts - really ANY kind of record, but usually...
# switches, routers, etc..
# Or service records

- name: "Ensure dns record state for - {{ idm_dns_record.name }}"
  redhat.rhel_idm.ipadnsrecord:
    ipaadmin_principal: "{{ ipa_admin_principal }}"                          # required
    ipaadmin_password: "{{ ipa_admin_password }}"                            # required
    name: "{{ idm_dns_record.name }}"                                        # required
    zone_name: "{{ idm_dns_record.zone_name }}"                              # required
    record_type: "{{ idm_dns_record.record_type | default(omit) }}"                          # required
    record_value: "{{ idm_dns_record.record_value | default(omit) }}"                        # required
    a_create_reverse: "{{ idm_dns_record.a_create_reverse | default(omit) }}"
    a_ip_address: "{{ idm_dns_record.a_ip_address | default(omit) }}"
    a_record: "{{ idm_dns_record.a_record_raw_list | default(omit) }}"
    aaaa_create_reverse: "{{ idm_dns_record.aaaa_create_reverse | default(omit) }}"
    aaaa_ip_address: "{{ idm_dns_record.aaaa_ip_address | default(omit) }}"
    aaaa_record: "{{ idm_dns_record.aaaa_record_raw_list | default(omit) }}"
    afsdb_hostname: "{{ idm_dns_record.afsdb_hostname | default(omit) }}"
    afsdb_record: "{{ idm_dns_record.afsdb_record_raw_list | default(omit) }}"
    afsdb_subtype: "{{ idm_dns_record.afsdb_subtype | default(omit) }}"
    cert_algorithm: "{{ idm_dns_record.cert_algorithm | default(omit) }}"
    cert_certificate_or_crl: "{{ idm_dns_record.cert_certificate_or_crl | default(omit) }}"
    cert_key_tag: "{{ idm_dns_record.cert_key_tag | default(omit) }}"
    cert_type: "{{ idm_dns_record.cert_type | default(omit) }}"             # Domain Validated, Org Validated, Extended Validation
    cname_hostname: "{{ idm_dns_record.cname_hostname | default(omit) }}"
    cname_record: "{{ idm_dns_record.cname_record_raw_list | default(omit) }}"
    create_reverse: "{{ idm_dns_record.create_reverse | default(omit) }}"
    del_all: "{{ idm_dns_record.del_all | default(omit) }}"
    dlv_algorithm: "{{ idm_dns_record.dlv_algorithm | default(omit) }}"     # DNSSEC Lookaside Valdation
    dlv_digest: "{{ idm_dns_record.dlv_digest | default(omit) }}"
    dlv_digest_type: "{{ idm_dns_record.dlv_digest_type | default(omit) }}"
    dlv_key_tag: "{{ idm_dns_record.dlv_key_tag | default(omit) }}"
    dlv_record: "{{ idm_dns_record.dlv_record_raw_list | default(omit) }}"
    dname_record: "{{ idm_dns_record.dname_record_raw_list | default(omit) }}"
    dname_target: "{{ idm_dns_record.dname_target | default(omit) }}"
    ds_algorithm: "{{ idm_dns_record.ds_algorithm | default(omit) }}"     # DNSSEC Lookaside Valdation
    ds_digest: "{{ idm_dns_record.ds_digest | default(omit) }}"
    ds_digest_type: "{{ idm_dns_record.ds_digest_type | default(omit) }}"
    ds_key_tag: "{{ idm_dns_record.ds_key_tag | default(omit) }}"
    ds_record: "{{ idm_dns_record.ds_record_raw_list | default(omit) }}"
    ip_address: "{{ idm_dns_record.ip_address | default(omit) }}"
    kx_exchanger: "{{ idm_dns_record.kx_exchanger | default(omit) }}"
    kx_preference: "{{ idm_dns_record.kx_preference | default(omit) }}"
    kx_record: "{{ idm_dns_record.kx_record_raw_list | default(omit) }}"
    loc_altitude: "{{ idm_dns_record.loc_altitude | default(omit) }}"         # Geographical Location records
    loc_h_precision: "{{ idm_dns_record.loc_h_precision | default(omit) }}"
    loc_lat_deg: "{{ idm_dns_record.loc_lat_deg | default(omit) }}"
    loc_lat_dir: "{{ idm_dns_record.loc_lat_dir | default(omit) }}"
    loc_lat_min: "{{ idm_dns_record.loc_lat_min | default(omit) }}"
    loc_lat_sec: "{{ idm_dns_record.loc_lat_sec | default(omit) }}"
    loc_lon_deg: "{{ idm_dns_record.loc_lon_deg | default(omit) }}"
    loc_lon_dir: "{{ idm_dns_record.loc_lon_dir | default(omit) }}"
    loc_lon_min: "{{ idm_dns_record.loc_lon_min | default(omit) }}"
    loc_lon_sec: "{{ idm_dns_record.loc_lon_sec | default(omit) }}"
    loc_record: "{{ idm_dns_record.loc_record_raw_list | default(omit) }}"
    loc_size: "{{ idm_dns_record.loc_size | default(omit) }}"
    loc_v_precision: "{{ idm_dns_record.loc_v_precision | default(omit) }}"
    mx_exchanger: "{{ idm_dns_record.mx_exchanger | default(omit) }}"
    mx_preference: "{{ idm_dns_record.mx_preference | default(omit) }}"
    mx_record: "{{ idm_dns_record.mx_record_raw_list | default(omit) }}"
    naptr_flags: "{{ idm_dns_record.naptr_flags | default(omit) }}"
    naptr_order: "{{ idm_dns_record.naptr_order | default(omit) }}"
    naptr_preference: "{{ idm_dns_record.naptr_preference | default(omit) }}"
    naptr_record: "{{ idm_dns_record.naptr_record_raw_list | default(omit) }}"
    naptr_regexp: "{{ idm_dns_record.naptr_regexp | default(omit) }}"
    naptr_replacement: "{{ idm_dns_record.naptr_replacement | default(omit) }}"
    naptr_service: "{{ idm_dns_record.naptr_service | default(omit) }}"
    ns_hostname: "{{ idm_dns_record.ns_hostname | default(omit) }}"
    ns_record: "{{ idm_dns_record.ns_record_raw_list | default(omit) }}"
    ptr_hostname: "{{ idm_dns_record.ptr_hostname | default(omit) }}"
    ptr_record: "{{ idm_dns_record.ptr_record_raw_list | default(omit) }}"
    record_ttl: "{{ idm_dns_record.record_ttl | default(omit) }}"
    records: "{{ idm_dns_record.records_raw_list | default(omit) }}"
    srv_port: "{{ idm_dns_record.srv | default(omit) }}"
    srv_priority: "{{ idm_dns_record.srv_priority | default(omit) }}"
    srv_record: "{{ idm_dns_record.srv_record_raw_list | default(omit) }}"
    srv_target: "{{ idm_dns_record.srv_target | default(omit) }}"
    srv_weight: "{{ idm_dns_record.srv_weight | default(omit) }}"
    sshfp_algorithm: "{{ idm_dns_record.sshfp_algorithm | default(omit) }}"
    sshfp_fingerprint: "{{ idm_dns_record.sshfp_fingerprint | default(omit) }}"
    sshfp_fp_type: "{{ idm_dns_record.sshfp_fp_type | default(omit) }}"
    sshfp_record: "{{ idm_dns_record.sshfp_record_raw_list | default(omit) }}"
    tlsa_cert_association_data: "{{ idm_dns_record.tlsa_cert_association_data | default(omit) }}"
    tlsa_cert_usage: "{{ idm_dns_record.tlsa_cert_usage | default(omit) }}"
    tlsa_matching_type: "{{ idm_dns_record.tlsa_matching_type | default(omit) }}"
    tlsa_record: "{{ idm_dns_record.tlsa_record_raw_list | default(omit) }}"
    tlsa_selector: "{{ idm_dns_record.tlsa_selector | default(omit) }}"
    txt_data: "{{ idm_dns_record.txt_data | default(omit) }}"
    txt_record: "{{ idm_dns_record.txt_record_raw_list | default(omit) }}"
    uri_priority: "{{ idm_dns_record.uri_priority | default(omit) }}"
    uri_record: "{{ idm_dns_record.uri_record_raw_list | default(omit) }}"
    uri_target: "{{ idm_dns_record.uri_target | default(omit) }}"
    uri_weight: "{{ idm_dns_record.uri_weight | default(omit) }}"
  tags:
    - tags_rhis_builder
    - tags_rhis_builder_idm
    - tags_idm_post_install
